directories:
  output: release
  buildResources: build
appId: com.leb2.workchecker
productName: LEB2 Work Checker
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
      - database/**/*
      - icon.ico
      - package.json
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  installerIcon: icon.ico
electronVersion: 44.3.0
